[project]
name = "se01webengineering"
version = "0.1.0"
description = "web app about the blog site for SE01webengineering"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.14.2",
    "dj-database-url>=3.1.2",
    "django>=6.0.6",
    "django-htmx>=1.28.0",
    "gunicorn>=26.0.0",
    "psycopg[binary]>=3.3.4",
    "pytest-django>=4.12.0",
    "ruff>=0.15.17",
    "whitenoise>=6.12.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "blog_prj.settings"
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
]
