# Generated by Django 6.0.6 on 2026-07-27 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
